---
repos:
 - repo: https://github.com/astral-sh/ruff-pre-commit
   rev: 895ebb389825c29bd4e0addcf7579d6c69d199cc  # frozen: v0.9.6
   hooks:
     - id: ruff
       types_or: [ python, pyi, jupyter ]
       args: [ --fix ]
     - id: ruff-format
       types_or: [ python, pyi, jupyter ]
 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: 31903eabdb97f5a3375fb1ea419ff782de64d7e7
   hooks:
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-shebang-scripts-are-executable
    - id: check-symlinks
    - id: check-yaml
    - id: detect-aws-credentials
      args: ['--allow-missing-credentials']
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: trailing-whitespace
 - repo: https://github.com/lycheeverse/lychee
   rev: d6bbf85145940fde88e079fd304c9b1603ff4265  # frozen: nightly
   hooks:
     - id: lychee-docker
       types: [markdown]
 - repo: https://github.com/rhysd/actionlint
   rev: 2ab3a12c7848f6c15faca9a92612ef4261d0e370
   hooks:
     - id: actionlint-docker
 - repo: https://github.com/koalaman/shellcheck-precommit
   rev: 2491238703a5d3415bb2b7ff11388bf775372f29  # frozen: v0.10.0
   hooks:
     - id: shellcheck
       args: [ -x, --source-path=SCRIPTDIR ]
 - repo: https://github.com/trufflesecurity/trufflehog
   rev: 52ae3c343cc6cc2817d9aa410227ac3b8a1b7684
   hooks:
     - id: trufflehog
       # Check the past 2 commits; it's useful to make this go further back than main when running this where main and HEAD are equal
       entry: trufflehog git file://. --since-commit main~1 --no-verification --fail
