---
- name: Run the Zenable CLI installer
  ansible.builtin.shell:
    cmd: set -o pipefail && curl -fsSL https://cli.zenable.app/install.sh | ZENABLE_NONINTERACTIVE=1 bash -s -- --yes
    creates: "{{ ansible_env.HOME }}/.zenable/bin/zenable"

- name: Install machine-wide
  become: true
  when: zenable_cli_machine_wide
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/.zenable/bin/zenable"
    dest: /usr/local/bin/zenable
    mode: "0755"
    remote_src: true

- name: Test the Zenable CLI
  ansible.builtin.command: /usr/local/bin/zenable version
  changed_when: false
