---
- name: Install prereq packages
  ansible.builtin.package:
    name:
      - ca-certificates
      - curl
      - jq
      - sudo
    state: latest

- name: Download get-docker.sh
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh

- name: Run get-docker.sh
  shell: "bash /tmp/get-docker.sh"
  args:
    creates: /usr/bin/docker

- name: Clean up get-docker.sh
  file:
    path: /tmp/get-docker.sh
    state: absent

- name: Add the current user to the docker group
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
