---
- name: Ensure supported OS
  ansible.builtin.assert:
    that:
      - ansible_os_family in ['Debian', 'RedHat']
    fail_msg: "This playbook only supports Debian and RedHat based systems."
  run_once: true

- name: Install prereqs (apt)
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl
      - jq
      - sudo
    update_cache: true
    install_recommends: no
  when: ansible_os_family == 'Debian'

- name: Install prereqs
  ansible.builtin.packages:
    name:
      - ca-certificates
      - curl
      - jq
      - sudo
    state: latest
  when: ansible_os_family == 'RedHat'

- name: Download get-docker.sh
  ansible.builtin.get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: "0755"

- name: Run get-docker.sh
  ansible.builtin.command: "bash /tmp/get-docker.sh"
  args:
    creates: /usr/bin/docker

- name: Clean up get-docker.sh
  ansible.builtin.file:
    path: /tmp/get-docker.sh
    state: absent

- name: Add the current user to the docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
