---
- name: Ensure supported OS
  ansible.builtin.assert:
    that:
      - ansible_os_family in ['Debian', 'RedHat']
    fail_msg: "This playbook only supports Debian and RedHat based systems."
  run_once: true

- ansible.builtin.include_role:
    name: docker

- name: Install repository for Debian (apt)
  block:
    - name: Setup apt key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.gpg

    - name: Setup apt repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      when: ansible_os_family == 'Debian'

- name: Install repository for Red Hat (yum)
  ansible.builtin.yum_repository:
    name: docker
    baseurl: https://download.docker.com/linux/rhel/docker-ce.repo
  when: ansible_os_family == 'RedHat'

- name: Install docker compose
  ansible.builtin.package:
    name:
      - docker-compose-plugin
    state: latest
