---
- name: Transfer resize script
  ansible.builtin.copy:
    src: resize-disk.sh
    dest: "{{ home_dir }}"
    mode: "0755"

- name: Resize the host disk to 40 GiB
  ansible.builtin.command:
    argv:
      - "{{ home_dir }}/resize-disk.sh"
      - 40
