---
- name: Install prereq python packages
  ansible.builtin.pip:
    name:
      - boto3
      - packaging
    state: latest

- name: Gather info needed to detect Cloud9 images
  block:
    - name: Gather EC2 metadata facts
      amazon.aws.ec2_metadata_facts:

    - name: Gather AMI details
      amazon.aws.ec2_ami_info:
        image_ids: "{{ ansible_ec2_ami_id }}"
        region: "{{ ansible_ec2_placement_region }}"
      register: ami_info

- name: Resize the host disk to 40 GiB and expand the partition mounted to /
  # Note: Amazon changes the Account ID ("owner_id") periodically
  # so we cannot restrict it in the below when clause
  when: >
    ami_info['images'][0]['image_location'].startswith('amazon/Cloud9') and
    ami_info['images'][0]['name'].startswith('Cloud9')
  block:
    - name: Transfer resize script
      ansible.builtin.copy:
        src: resize-disk.sh
        dest: "{{ home_dir }}"
        mode: "0755"

    - name: Resize the host disk to 40 GiB
      ansible.builtin.command:
        argv:
          - "{{ home_dir }}/resize-disk.sh"
          - 40

    - name: Transfer disk checking script
      ansible.builtin.copy:
        src: check-partition.sh
        dest: "{{ home_dir }}"
        mode: "0755"

    # This is checking for 40GB not GiB to give some breathing room
    - name: Ensure the host disk is at least 40 GB
      ansible.builtin.command:
        argv:
          - "{{ home_dir }}/check-partition.sh"
          - 40
