---
- name: Install prereq python packages
  ansible.builtin.pip:
    name: boto3
    state: latest

- name: Gather info needed to detect Cloud9 images
  block:
    - name: Gather EC2 metadata facts
      amazon.aws.ec2_metadata_facts:

    - name: Gather AMI details
      amazon.aws.ec2_ami_info:
        image_ids: "{{ ansible_ec2_ami_id }}"
      register: ami_info

- name: Resize the host disk to 40 GiB
  when: >
    ami_info['images'][0]['image_location'].startswith('amazon/Cloud9') and
    ami_info['images'][0]['name'].startswith('Cloud9') and
    ami_info['images'][0]['owner_id'] == '845575274112'
  block:
    - name: Transfer resize script
      ansible.builtin.copy:
        src: resize-disk.sh
        dest: "{{ home_dir }}"
        mode: "0755"

    - name: Resize the host disk to 40 GiB
      ansible.builtin.command:
        argv:
          - "{{ home_dir }}/resize-disk.sh"
          - 40
