- name: Check if resize script touchfile exists
  ansible.builtin.stat:
    path: "/tmp/.resize-disk"
  register: touchfile_info
  ignore_errors: true

- name: Transfer resize script
  ansible.builtin.copy:
    src: resize-disk.sh
    dest: "{{ home_dir }}"
    mode: "0755"
  when: script_info.stat.exists == "false"

- name: Resize the host disk to 40 GiB
  ansible.builtin.command:
    argv:
      - "{{ home_dir }}/resize-disk.sh"
      - 40
    creates: /tmp/.resize-disk
  when: touchfile_info.stat.exists == "false"
