---
- name: Ensure supported OS
  ansible.builtin.assert:
    that:
      - ansible_os_family in ['Debian', 'RedHat']
    fail_msg: "This playbook only supports Debian and RedHat based systems."
  run_once: true

- name: Install linuxbrew
  block:
    - name: Download linuxbrew installer
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
        dest: /tmp/install-homebrew.sh
        mode: "0755"
    - name: Install linuxbrew
      ansible.builtin.command:
        cmd: echo | /tmp/install-homebrew.sh
    - name: Add brew to path
      become: true
      copy:
        dest: /etc/profile.d/brew.sh
        content: 'PATH=$PATH:/home/linuxbrew/.linuxbrew/bin'
    - name: Ensure $HOME/bin exists
      ansible.builtin.file:
        path: "{{ home_dir }}/bin"
        state: directory
    - name: Setup a symlink
      ansible.builtin.file:
        src: "{{ home_dir }}/bin/brew"
        dest: /home/linuxbrew/.linuxbrew/Homebrew/bin/brew
        state: link
